### ISSUE TITLE
Consider new structure for unit tests

### ISSUE THREAD

**Issue by minijus** [open-kudos/open-kudos-intern-web#223]
I would suggest to structure unit tests in two possible ways:
1. Keep them in same folder where testable file resides. Meaning tests for profile.controller.js would be placed in src/app/profile/profile.controller.spec.js
2. Replicate app structure in test folder. Meaning tests for profile.controller.js would be placed in test/app/profile/profile.controller.spec.js or test/profile/profile.controller.spec.js (if you would move assests out from src folder).

@Medds what do you think - is it good option to place tests near the file that is being tested?

I would not place test folder inside src as well.

Also, do not merge commented out code into integration: https://github.com/open-kudos/open-kudos-intern-web/blob/master/src/test/team-challenge.spec.js#L141-L162

**Comment by Medds** [comment]
The file/test in the same folder structure works fine as long as everything is structured properly and grouped into a component-like structure, because things can quickly get out of hand when keeping many files on the same level.
