### ISSUE TITLE
Send email after giving challenge to participant

### ISSUE THREAD

**Issue by Cerkute** [open-kudos/open-kudos-intern-web#229]
Content of email:
'You got the challenge from" challenge sender's name": "challenge description" for "Y" acorns. Let "challenge sender's name" know if you accept the challenge in your Openkudos account!'

In the bottom of the email there should be a text saying:
"If you don't want to receive notifications about new challenges, unsubscribe here." 

The link should lead to the settings page (if user is logged in to his/her account already).

**Comment by vytautassugintas** [comment]
to subscribe use [POST] user/subscribe
to unsubscribe use [POST] user/unsubscribe

will work on email sending
